ReleaseNotes.md

Add documentation for JARVICE API concurrent limits

---

templates/jarvice-daemonsets.yaml
terraform/modules/gke/locals.tf
values.yaml

- Added init delay for dri-optional daemonset 

GKE updates for dri-optional

---

templates/jarvice-api.yaml
values.yaml

Update jarvice_api for parallel processing /jarvice/apps

---

README.md

Update doc for registry proxy for application containers

---

templates/jarvice-api.yaml
templates/jarvice-mc-portal.yaml
values.yaml

[JAR-4240] Add JARVICE_API_URL to values

---

templates/jarvice-api.yaml
templates/jarvice-mc-portal.yaml
values.yaml

[JAR-4240] Add JARVICE_API_URL

---

Configuration.md

already reviewed by @randyorr as well.

JAR-4294: documentation updates

---

LicenseManager.md
templates/jarvice-license-manager.yaml
templates/jarvice-mc-portal.yaml

lts branch for jar4501

---

Storage.md
templates/jarvice-k8s-scheduler.yaml
values.yaml

JAR-5575 Make pvcrun resources configurable

---

terraform/modules/gke/outputs.tf

JAR-5308 Use kubectl exec plugin for GKE after k8s 1.26

---

InfiniBandCNI.md

remove unneeded crd

---

jarvice-settings/admin_invite.mailtemplate
jarvice-settings/email.head
jarvice-settings/email.tail
jarvice-settings/eula.txt
jarvice-settings/forgot_password.mailtemplate
jarvice-settings/signup_request_team.mailtemplate
jarvice-settings/signup_success.mailtemplate

Updates broken links that still pointed to nimbix.net

Update broken URLS

---

files/jarvice-bird-config.json
files/jarvice-bird-nginx.conf
templates/jarvice-bird-portal.yaml
templates/jarvice-bird-server.yaml
templates/jarvice-bird.yaml
templates/jarvice-storageclasses.yaml
terraform/modules/common/locals.tf
values.yaml

add bird portal

---

README.md

changed readme file to add how to configure content in about page

 changed readme file

---

values.yaml

JAR-7150: increase minimum default size of overlay to better accommodate certain apps

---

terraform/modules/eks/main.tf
terraform/terraform.tfvars

AWS GPU device tag's for AWS autoscaling from 0.

Adding AWS tags for GPU devices for AWS scale from 0 issue.

---

templates/jarvice-helm-hook.yaml

Helm hook bird url changes

---

templates/jarvice-api.yaml
templates/jarvice-bird.yaml
templates/jarvice-mc-portal.yaml

update JARVICE_API_PUBLIC_URL path

JAR-8308 update JARVICE_API_PUBLIC_URL path

---

files/jarvice-bird-nginx.conf.template

3.24.0-rc - JAR-8325

---

templates/_helpers.tpl

set version based on JARVICE_IMAGES_VERSION or Chart.Annotations.version

JAR-8351 - Fix generator for container image tags

---

LicenseManager.md
README.md

job submission validation hook script

JAR-8150 - Add job validation hook script

---

templates/jarvice-bird.yaml
terraform/modules/common/locals.tf

* fix k8s dns domain in BIRD deployment
* add dns_domain key to terraform

JAR-8452 - Make service DNS domain configurable

---

terraform/modules/helm/main.tf

As the title states - Keycloak repeatedly fails to initialise keycloak on a helm deployment. Can be initialised by querying /auth once for a 200 response, at which point everything springs into life.
Added a http check to terraform as a result.

JAR-9238: Fix keycloak initialisation by querying /auth on deploy

---

templates/jarvice-kns-scheduler.yaml
terraform/modules/gkev2/deploy.tf
terraform/modules/gkev2/main.tf
terraform/modules/gkev2/variables.tf
terraform/terraform.tfvars
terraform/variables.tf
values.yaml

As per description - Adds a new node pool type to add KNS support, works on SC24 cluster demo platform.

Add jarvice KNS pool support to GKEv2

---

Storage+Management.md

Added a new md file for the Storage Management document.

Storage Management 

---

scripts/jarvice-pull-apps
scripts/jarvice-pull-system-images

Update jarvice-pull-apps to create "jarvice" user to use as "owner" for new apps
Update jarvice-pull-system-images to locate certain image patterns not previously found

JAR-10247: edit pull scripts

---

values.yaml

References in the new lxcfs container built via our main jarvice repo.

Fix: JAR-10451 - Add new lxcfs image to lxcfs-daemonset values.yaml
